application: lysender-com-py
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico
- url: /media
  static_dir: media
- url: /.*
  script: web.app
