---
index:
  section:
    slot: 1
    value: 'Home Page'
  sub_section:
    slot: 2
    value: 'Home Page'
about:
  section:
    slot: 1
    value: 'About Us'
  sub_section:
    slot: 2
    value: 'About Us'
projects:
  section:
    slot: 1
    value: 'Projects'
  sub_section:
    slot: 2
    value: 'Projects Index'
projects_chrometito:
  section:
    slot: 1
    value: 'Projects'
  sub_section:
    slot: 2
    value: 'Projects - Chrome TITO'
extras:
  section:
    slot: 1
    value: 'Extras'
  sub_section:
    slot: 2
    value: 'Extras Index'
extras_sprint:
  section:
    slot: 1
    value: 'Extras'
  sub_section:
    slot: 2
    value: 'Extras - Sprint'
extras_sprint_letter:
  section:
    slot: 1
    value: 'Extras'
  sub_section:
    slot: 2
    value: 'Extras - Sprint Letter'
tools:
  section:
    slot: 1
    value: 'Tools'
  sub_section:
    slot: 2
    value: 'Tools Index'
tools_base64:
  section:
    slot: 1
    value: 'Tools'
  sub_section:
    slot: 2
    value: 'Tools - Base64'
tools_sumfirstcol:
  section:
    slot: 1
    value: 'Tools'
  sub_section:
    slot: 2
    value: 'Tools - Sum First Column'
tools_urlencode:
  section:
    slot: 1
    value: 'Tools'
  sub_section:
    slot: 2
    value: 'Tools - URL Encode'
tools_worldclock:
  section:
    slot: 1
    value: 'Tools'
  sub_section:
    slot: 2
    value: 'Tools - World Clock'
tools_worldclock_specific:
  section:
    slot: 1
    value: 'Tools'
  sub_section:
    slot: 2
    value: 'Tools - World Clock Specific'
contact:
  section:
    slot: 1
    value: 'Contact'
  sub_section:
    slot: 2
    value: 'Contact'