# Read more: http://wiki.answers.com/Q/What_are_some_adjectives_that_begin_with_the_letter_E#ixzz1et9La9m5
# Read more: http://wiki.answers.com/Q/What_animals_start_with_the_letter_e#ixzz1et9dehlQ

adjectives:
  - hilarious
  - honeyed
  - homely
  - honored
  - happy
  - harsh
  - hinged
  - hungry
  - humorous
  - horny
  - helpful
  - hopeful
  - habile
  - habilable
  - hadeharia
  - haemathermal
  - hematic
  - halitosis
  - halophilous
  - hamiform
  - haptotropic
  - harengiform
  - heterotrichosis
  - heady
  - hateful
  - hot
  - harrowing
  - hallow
  - haggard
  - Haughty
  - Happy
  - Humorous
  - Healthy
  - Hopeful
  - huggable
  - hilarious
  - happy
  - hip
  - huggable
  - hilarious
  - happy

animals:
  - Hawk
  - Hamster
  - Hare
  - Hummingbird
  - Heifer
  - Hen
  - Hippopotamus
  - Hog
  - Horse
  - Human
  - Haddock
  - Halibut
  - Hammerhead Shark
  - Honeybee
  - Hornet
  - Horsefly
  - Hyena
